In [1]:
#Write a program to create a 5 dimensional array with all zeros and ones

In [2]:
import numpy as np

In [59]:
arr1=np.random.randint(2,size=(2,2,2,2,2))
arr1

array([[[[[0, 1],
          [1, 0]],

         [[0, 0],
          [0, 0]]],


        [[[0, 1],
          [1, 0]],

         [[1, 0],
          [1, 1]]]],



       [[[[1, 1],
          [0, 0]],

         [[1, 1],
          [0, 0]]],


        [[[0, 1],
          [1, 0]],

         [[0, 0],
          [1, 1]]]]])

In [2]:
#Write a program to create an array of 10 zeros,10 ones, and 10 fives in row 1 2 and 3 which create a new array of shape (3,10)

In [63]:
arr1=np.array([[0,0,0,0,0,0,0,0,0,0],[1,1,1,1,1,1,1,1,1,1],[5,5,5,5,5,5,5,5,5,5]])
arr1

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [3]:
#Write a program to create a 3x4 matrix filled with values from 10 to 21.

In [60]:
arr1=np.arange(10,22).reshape(3,4)
arr1

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [4]:
#Write a  program to create a 10x10 zero matrix with elements on the main diagonal equal to 0,1,2,3,4,5,6,7,8,9,

In [57]:
arr1=np.diag([1,2,3,4,5,6,7,8,9])
arr1

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [5]:
#Write a program to create a 4x4 array. Create an array from below array by swapping first and last, second and third columns.

In [44]:
arr1=np.arange(1,17).reshape(4,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [45]:
arr1[::,::-1]

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9],
       [16, 15, 14, 13]])

In [6]:
#Write a program to reverse an array (the first element becomes the last).
#Given array:
#[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 ]

In [37]:
arr=np.array([12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27])
arr[::-1]

array([27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12])

In [7]:
#Write a program to access all the elements greater than 30 and less than 80 and multiples of 5 from an array of shape 10,10.
#Elements range from 1 to 100

In [20]:
arr1=np.arange(1,101).reshape(10,10)
arr1

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [33]:
(arr1>30) & (arr1<80) & (arr1%5==0)

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False,  True, False, False, False, False,
         True],
       [False, False, False, False,  True, False, False, False, False,
         True],
       [False, False, False, False,  True, False, False, False, False,
         True],
       [False, False, False, False,  True, False, False, False, False,
         True],
       [False, False, False, False,  True, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [34]:
arr1[(arr1>30) & (arr1<80) & (arr1%5==0)]

array([35, 40, 45, 50, 55, 60, 65, 70, 75])

In [8]:
#Write a program to create a 2D array with 1 on the border and 0 inside.

In [41]:
arr1=np.ones((4,4),dtype=int)
arr1

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [45]:
arr1[[1,1,2,2],[1,2,1,2]]=0
arr1

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

In [71]:
#Write a program to create a checkerboard pattern .Don't use default array function
#Checkerboard pattern:                                                   
#[[0 1 0 1 0 1 0 1]                                                      
# [1 0 1 0 1 0 1 0]                                                      
# [0 1 0 1 0 1 0 1]                                                      
# [1 0 1 0 1 0 1 0]                                                      
# [0 1 0 1 0 1 0 1]                                                      
# [1 0 1 0 1 0 1 0]  
# [0 1 0 1 0 1 0 1]                                                      
# [1 0 1 0 1 0 1 0]]

In [33]:
arr1=np.zeros((8,8),dtype=int)
arr1

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [46]:
arr1[arr1%2==0]=1
arr1

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [10]:
#Write a program to find common values between two arrays.
#Expected Output:
#array1: [10 20 40 60]
#array2: [10, 30, 40,50]

In [33]:
arr1=np.array([10,20,40,60])
arr2=np.array([10,30,40,50])
print(arr1)
print(arr2)

[10 20 40 60]
[10 30 40 50]


In [36]:
arr2[arr1==arr2]

array([10, 40])

In [11]:
#Write a program to create an array 2d array and then reshape into 1d array

In [35]:
arr1=np.array([[1,2,3,4],[5,6,7,9],[10,11,21,13],[14,15,16,18]])
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  9],
       [10, 11, 21, 13],
       [14, 15, 16, 18]])

In [18]:
arr1.reshape(16,)

array([ 1,  2,  3,  4,  5,  6,  7,  9, 10, 11, 21, 13, 14, 15, 16, 18])

In [12]:
#Write a user defined function for creating a 1 or 2d array from scratch without using array functions

In [7]:
def create_1d_array(size,value):
    array=[]
    for i in range(size):
        array.append(value)
    return array
result=create_1d_array(size=5,value=6)
print(result)
np.array(result)

[6, 6, 6, 6, 6]


array([6, 6, 6, 6, 6])